export interface MockProduct {
  id: string
  slug: string
  name: string
  brand: string
  era: 'VINTAGE' | 'MODERN'
  year: number
  description: string
  price: number // 49.99 € TTC
  isActive: boolean
  isFeatured: boolean
  images: string[]
  variants: {
    id: string
    sku: string
    stock: number
    stockAlert: number
  }[]
}

export const MOCK_PRODUCTS: MockProduct[] = [
  // ─── SUPERCARS D'ÉLITE (COLLECTION AUTHENTIQUE) ──────────────────────────────
  {
    id: 'real-bugatti-chiron',
    slug: 'bugatti-chiron-2016-cadre-3d',
    name: 'Bugatti Chiron (2016)',
    brand: 'Bugatti',
    era: 'MODERN',
    year: 2016,
    description: "Le sommet du luxe et de l'hypercar W16 1 500 ch. Cadre d'ébénisterie 3D avec éclairage LED ambré, immortalisé devant la véritable Bugatti Chiron.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: [
      '/atelier/chiron-wall.jpg',
      '/atelier/chiron-trunk.jpg',
    ],
    variants: [{ id: 'var-chiron', sku: 'DF-BUGATTI-CHIRON', stock: 5, stockAlert: 2 }],
  },
  {
    id: 'real-pagani-huayra',
    slug: 'pagani-huayra-v12-cadre-3d',
    name: 'Pagani Huayra V12',
    brand: 'Pagani',
    era: 'MODERN',
    year: 2023,
    description: "L'artisanat automobile italien dans ce qu'il a de plus pur. V12 Biturbo AMG de 730 ch sous châssis Carbo-Titane, photographié à côté de son modèle échelle 1.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/atelier/huayra-real.jpg'],
    variants: [{ id: 'var-huayra', sku: 'DF-PAGANI-HUAYRA', stock: 4, stockAlert: 2 }],
  },
  {
    id: 'real-audi-r8v10',
    slug: 'audi-r8-v10-performance-cadre-3d',
    name: 'Audi R8 V10 Performance',
    brand: 'Audi',
    era: 'MODERN',
    year: 2022,
    description: "Le rugissement du V10 atmosphérique à 8 700 tr/min. Cadre 3D relief sous vitrage acrylique HD avec rétroéclairage LED ambré.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/atelier/r8v10-real.jpg'],
    variants: [{ id: 'var-r8v10', sku: 'DF-AUDI-R8V10', stock: 7, stockAlert: 3 }],
  },
  {
    id: 'real-bmw-m4comp',
    slug: 'bmw-m4-competition-isle-of-man-cadre-3d',
    name: 'BMW M4 Competition (G82)',
    brand: 'BMW',
    era: 'MODERN',
    year: 2023,
    description: "Teinte mythique Isle of Man Green et calandre verticale acérée. Réalisation 3D de précision sous vitrage acrylique.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/atelier/m4comp-real.jpg'],
    variants: [{ id: 'var-m4comp', sku: 'DF-BMW-M4COMP', stock: 6, stockAlert: 2 }],
  },
  {
    id: 'real-lambo-huracan',
    slug: 'lamborghini-huracan-lp-610-4-cadre-3d',
    name: 'Lamborghini Huracán LP 610-4',
    brand: 'Lamborghini',
    era: 'MODERN',
    year: 2021,
    description: "V10 atmosphérique 5.2L et arêtes tranchantes stealth. Cadre d'artisanat avec module LED ambré et finitions haut de gamme.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/atelier/huracan-real.jpg'],
    variants: [{ id: 'var-huracan', sku: 'DF-LAMBO-HURACAN', stock: 5, stockAlert: 2 }],
  },
  {
    id: 'real-mercedes-amggtr',
    slug: 'mercedes-amg-gt-r-2017-cadre-3d',
    name: 'Mercedes-AMG GT R (2017)',
    brand: 'Mercedes-Benz',
    era: 'MODERN',
    year: 2017,
    description: "La bête de l'Enfer Vert Nürburgring. V8 Biturbo 4.0L sous châssis aluminium et vitrage acrylique optique HD.",
    price: 49.99,
    isActive: true,
    isFeatured: false,
    images: ['/atelier/amggtr-real.jpg'],
    variants: [{ id: 'var-amggtr', sku: 'DF-MERCEDES-AMGGTR', stock: 4, stockAlert: 2 }],
  },
  {
    id: 'real-mclaren-gt',
    slug: 'mclaren-gt-2019-cadre-3d',
    name: 'McLaren GT (2019)',
    brand: 'McLaren',
    era: 'MODERN',
    year: 2019,
    description: "L'élégance Grand Tourisme britannique en relief 3D. V8 Biturbo 620 ch sous cadre d'artisanat bois et éclairage LED supérieur.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/images/frames/frame-mclaren-gt.jpg'],
    variants: [{ id: 'var-mclarengt', sku: 'DF-MCLAREN-GT', stock: 5, stockAlert: 2 }],
  },
  {
    id: 'real-audi-r8v10',
    slug: 'audi-r8-v10-performance-cadre-3d',
    name: 'Audi R8 (2018)',
    brand: 'Audi',
    era: 'MODERN',
    year: 2018,
    description: "Le rugissement du V10 atmosphérique à 8 700 tr/min. Cadre 3D relief sous vitrage acrylique HD avec rétroéclairage LED ambré.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/images/frames/frame-audi-r8.jpg'],
    variants: [{ id: 'var-r8v10', sku: 'DF-AUDI-R8V10', stock: 7, stockAlert: 3 }],
  },
  {
    id: 'real-porsche-cayenne',
    slug: 'porsche-cayenne-turbo-2016-cadre-3d',
    name: 'Porsche Cayenne Turbo (2016)',
    brand: 'Porsche',
    era: 'MODERN',
    year: 2016,
    description: "La puissance souveraine du V8 Biturbo 570 ch. Silhouette musclée immortalisée en cadre d'artisanat d'art contemporain.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/images/frames/frame-porsche-cayenne.jpg'],
    variants: [{ id: 'var-cayenne', sku: 'DF-PORSCHE-CAYENNE', stock: 6, stockAlert: 2 }],
  },
  {
    id: 'real-ferrari-f40',
    slug: 'ferrari-f40-1987-cadre-3d',
    name: 'Ferrari F40 (1987)',
    brand: 'Ferrari',
    era: 'VINTAGE',
    year: 1987,
    description: "Le mythe absolu de Maranello. V8 Twin-Turbo et aileron légendaire sculptés au millimètre sous vitrage d'exception.",
    price: 49.99,
    isActive: true,
    isFeatured: true,
    images: ['/images/frames/frame-ferrari-f40.jpg'],
    variants: [{ id: 'var-f40', sku: 'DF-FERRARI-F40', stock: 4, stockAlert: 2 }],
  },
  {
    id: 'real-porsche-918',
    slug: 'porsche-918-spyder-2015-cadre-3d',
    name: 'Porsche 918 Spyder (2015)',
    brand: 'Porsche',
    era: 'MODERN',
    year: 2015,
    description: "L'hypercar hybride absolue de 887 ch. V8 atmosphérique et échappements hauts sculptés en relief 3D.",
    price: 49.99,
    isActive: true,
    isFeatured: false,
    images: ['/atelier/porsche918-real.jpg'],
    variants: [{ id: 'var-porsche918', sku: 'DF-PORSCHE-918', stock: 4, stockAlert: 2 }],
  },
]
